import type { JsonObject, Manifest, Redactor } from '@tecera/contracts';
import { renderPermissions, type PermissionsDoc } from '@tecera/policy';
import { stripMarkers } from './merge.js';

/**
 * Renderers for host adapters. `render:brain-summary` is the always-on context a host reads (memory slots,
 * permissions view, skills index, the done rule). `render:permissions` is the Claude Code settings
 * fragment: a deny list derived from `never` + `policy.protectedPaths`, and the PreToolUse/Stop hooks that
 * call back into `tecera hook`. Hosts get deny lists and hooks; enforcement proper is `tecera run`.
 * Everything rendered (memory slots, permissions view, skills index, settings) passes through the shared
 * redactor before it can reach a host prompt file. The PreToolUse matcher is `*`: every host tool goes
 * through the hook, which refuses tools it does not know to be read-only (hook.ts).
 */

export interface RenderSource {
  manifest: Manifest;
  permissions: PermissionsDoc;
  /** Read a file relative to the business-case root (staged or on disk). */
  read(rel: string): string | undefined;
  goals: string[];
  /** The runtime's redactor (resolved credentials, canaries, credential-shaped env values, key patterns). */
  redactor: Redactor;
}

export const HOOK_PRE_TOOL = 'tecera hook pre-tool';
export const HOOK_STOP = 'tecera hook stop';
export const EDIT_TOOLS = ['Edit', 'Write', 'MultiEdit', 'NotebookEdit'] as const;

/** `never` actions that map onto host command patterns. Unmapped actions are enforced by the pre-tool hook. */
export const NEVER_TO_DENY: Record<string, string[]> = {
  git_push: ['Bash(git push:*)'],
  open_pr: ['Bash(gh pr create:*)'],
  merge: ['Bash(git merge:*)', 'Bash(gh pr merge:*)'],
};

/**
 * Actions only the PR gate performs, on the human grant it consumes (D6). A host assistant never holds such
 * a grant, so they are denied to it like `never` actions even though permissions.json lists them under
 * requiresApproval.
 */
export const PR_GATE_ONLY = ['git_push', 'open_pr'] as const;

const TOOL_NAME = /^(?:[A-Z][A-Za-z0-9]*|mcp__[A-Za-z0-9_-]+)$/;

/** `never` entries shaped like host tool names (e.g. `WebFetch`) are denied as tools. */
export function neverTools(p: PermissionsDoc): string[] {
  return p.never.filter((a) => TOOL_NAME.test(a));
}

function demote(md: string, by: number): string {
  return md
    .split('\n')
    .map((l) => (/^#{1,6}\s/.test(l) ? '#'.repeat(by) + l : l))
    .join('\n');
}

const code = (s: string): string => `\`${s}\``;

export function renderBrainSummary(src: RenderSource, host: string): string {
  const m = src.manifest;
  const out: string[] = [];
  out.push(`## Tecera: ${m.name} (${m.id})`);
  out.push('');
  out.push(`Generated by \`tecera adapters install ${host}\`. Edit \`tecera.json\` and \`.tecera/\`, not this block.`);
  out.push('');
  out.push(`- Done means ${code(m.verify.command)} exits 0, proven: a run's goal.achieved carries the verify evidence. A returned answer is never done.`);
  out.push(`- Change only: ${m.repo.allowedChanges.map(code).join(', ') || '(nothing)'}`);
  out.push(`- Never edit: ${m.policy.protectedPaths.map(code).join(', ')}`);
  out.push(`- Goals: ${src.goals.length ? src.goals.map(code).join(', ') : '(none yet)'}. Before saying a goal is done, run ${code('tecera gate <goal>')}.`);
  out.push(`- Delivery: Tecera commits to the work branch ${code(`${m.repo.branchPrefix}<goal>`)}; a human approves the PR (${code('tecera approve <request>')}); nobody merges from here.`);
  if (host === 'claude-code') out.push(`- Hooks: ${code(HOOK_PRE_TOOL)} blocks edits outside the allowed paths; ${code(HOOK_STOP)} blocks stopping while a Tecera run is active without a goal.achieved proof.`);
  else out.push(`- This host runs no tecera hooks: call ${code('tecera gate <goal>')} yourself before you stop.`);
  const slot = (title: string, rel: string): void => {
    const text = src.read(rel);
    if (text === undefined) return;
    out.push('', `### ${title}`, '', demote(stripMarkers(text).trim(), 3));
  };
  slot('Preferences (always on)', '.tecera/memory/personal/PREFERENCES.md');
  slot('Workspace (always on)', '.tecera/memory/working/WORKSPACE.md');
  out.push('', '### Permissions', '', demote(renderPermissions(src.permissions), 3));
  slot('Skills', '.tecera/skills/_index.md');
  return src.redactor.redactText(out.join('\n'));
}

export function renderPermissionsSettings(src: RenderSource): JsonObject {
  const deny: string[] = [];
  for (const g of src.manifest.policy.protectedPaths) deny.push(`Edit(${g})`);
  for (const a of src.permissions.never) for (const d of NEVER_TO_DENY[a] ?? []) deny.push(d);
  for (const a of PR_GATE_ONLY) if (src.permissions.requiresApproval.includes(a)) for (const d of NEVER_TO_DENY[a] ?? []) deny.push(d);
  for (const t of neverTools(src.permissions)) deny.push(t);
  const matcher = '*';
  return src.redactor.redactJson({
    permissions: { deny: [...new Set(deny)] },
    hooks: {
      PreToolUse: [{ matcher, hooks: [{ type: 'command', command: HOOK_PRE_TOOL }] }],
      Stop: [{ hooks: [{ type: 'command', command: HOOK_STOP }] }],
    },
  }) as JsonObject;
}
